- name: play1
  hosts: servera
  tasks:
  - name: task1
    debug: 
      #var: ansible_facts.devices.vda.partitions.vda1.size
      #var: ansible_devices.vda.partitions.vda1.size
      var: ansible_facts.ansible_local.alp.custom.db_package 
