#
- name: partition play
  hosts: all
  gather_facts: no
  tasks:
  - name: create partition 1
    parted: 
      device: /dev/vdb
      number: 1
      state: present
      part_end: 65MiB

  - name: create partition 2
    parted: 
      device: /dev/vdb
      number: 2
      state: present
      part_start: 65MiB
      part_end: 129MiB

  - name: create partition 3
    parted: 
      device: /dev/vdb
      number: 3
      state: present
      part_start: 129MiB
      part_end: 193MiB

  - name: create extended partition
    parted: 
      device: /dev/vdb
      number: 4
      state: present
      part_start: 193MiB
      part_end: 100%
      part_type: extended

  - name: create 1st logical partition
    parted: 
      device: /dev/vdb
      number: 5
      state: present
      part_start: 194MiB
      part_end: 322MiB
      part_type: logical

  - name: create 2nd logical partition
    parted: 
      device: /dev/vdb
      number: 6
      state: present
      part_start: 323MiB
      part_end: 100%
      part_type: logical
      flags: [ lvm ]
