- name: Enable intranet services
  hosts: servera
  gather_facts: no
  tasks:
    - name: Latest version of httpd and firewalld installed
      ansible.builtin.dnf:
        name:
          - httpd
          - firewalld
        state: latest

    - name: Test html page is installed
      ansible.builtin.copy:
        content: "welcome to {{ inventory_hostname }}!\n"
        dest: /var/www/html/index.html

    - name: Firewall enabled and running
      ansible.builtin.service:
        name: firewalld
        enabled: true
        state: started

    - name: Firewall permits access to httpd service
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Web server enabled and running
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

- name: Test intranet web server
  hosts: localhost
  gather_facts: no
  become: false
  tasks:
  - name: Connect to intranet web server
    ansible.builtin.uri:
      url: http://servera.lab.example.com
      return_content: true
      status_code: 200
    register: sonuc

      #  - debug:
      #      var: sonuc
      #
  - set_fact:
      match: "{{ (sonuc.content is search('welcom.*')) | default('') }}"

  - name: Fail if webserver does not return proper content
    fail:
      msg: "Istenen icerik elde edilemedi"
        #when: "'welcom' not in sonuc.content"
    when: match == ''

